const SUPABASE_URL='https://swgftnwqydxkgvskqcpd.supabase.co';
const SUPABASE_KEY='sb_publishable_5zsfMElpPLFbIGklw6pgyw_nya87wH0';
const sb=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const WHATSAPP='254769604872';
const money=n=>'KSh '+Number(n||0).toLocaleString('en-KE');
let products=[],services=[],cart=JSON.parse(localStorage.getItem('namhara_cart')||'[]');
const $=id=>document.getElementById(id);
function toast(t){const e=$('toast');if(!e)return;e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2500)}
function productStock(p){const a=Number(p?.stock);const b=Number(p?.stock_count);return Math.max(Number.isFinite(a)?a:0,Number.isFinite(b)?b:0)}
function saveCart(){localStorage.setItem('namhara_cart',JSON.stringify(cart));renderCart();if($('cartCount'))$('cartCount').textContent=cart.reduce((a,b)=>a+b.quantity,0)}
function addToCart(p){const stock=productStock(p);if(!p||stock<=0)return toast('This product is out of stock');const x=cart.find(i=>String(i.id)===String(p.id));if(x){if(x.quantity>=stock)return toast('You have reached available stock');x.quantity++}else cart.push({id:p.id,name:p.name,price:Number(p.price||0),quantity:1,stock});saveCart();toast(p.name+' added to cart')}
function renderProducts(list=products){const box=$('products');if(!box)return;box.innerHTML=list.length?list.map(p=>{const stock=productStock(p);return `<article class="card"><div class="card-media" ${p.image_url?`style="background-image:url('${String(p.image_url).replace(/'/g,"%27")}')"`:``}>${p.image_url?'':'NAMHARA'}</div><div class="card-body"><div class="cat">${escapeHtml(p.category||'CAR CARE')}</div><h3>${escapeHtml(p.name)}</h3><p>${escapeHtml(p.description||'Premium car-care product.')}</p><div class="price">${money(p.price)}</div><div class="stock">${stock>0?stock+' in stock':'Out of stock'}</div><button type="button" class="goldBtn productAddBtn" data-product-id="${escapeHtml(String(p.id))}" ${stock>0?'':'disabled'}>ADD TO CART</button></div></article>`}).join(''):'<div class="empty">No products are currently available.</div>'}
function renderServices(){const box=$('servicesGrid');if(!box)return;const list=services.length?services:DEFAULT_SERVICES;box.innerHTML=list.map(s=>`<article class="service-card"><div class="service-icon">✦</div><h3>${escapeHtml(s.name)}</h3><p>${escapeHtml(s.description||'Professional vehicle care service.')}</p><button type="button" class="outlineBtn serviceBookBtn" data-service-name="${escapeHtml(s.name)}">BOOK THIS SERVICE</button></article>`).join('');if($('serviceSelect'))$('serviceSelect').innerHTML='<option value="">Select a service</option>'+list.map(s=>`<option value="${escapeHtml(s.name)}">${escapeHtml(s.name)}</option>`).join('')}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
const DEFAULT_SERVICES=[{name:'Full Car Wash & Detailing',description:'Professional exterior and interior cleaning.'},{name:'Wax & Paint Protection',description:'Deep shine, paint care and protective finish.'},{name:'Interior Deep Cleaning',description:'Detailed interior cleaning and freshening.'}];
function renderCart(){const box=$('cartItems');if(!box)return;if(!cart.length){box.innerHTML='<div class="empty">Your cart is empty.</div>';if($('cartSubtotal'))$('cartSubtotal').textContent=money(0);if($('cartDelivery'))$('cartDelivery').textContent=money(0);if($('cartTotal'))$('cartTotal').textContent=money(0);return}let subtotal=cart.reduce((a,b)=>a+Number(b.price)*b.quantity,0),delivery=subtotal>=5000?0:300;box.innerHTML=cart.map((i,idx)=>`<div class="cart-row"><div><strong>${escapeHtml(i.name)}</strong><div class="small">${money(i.price)} each</div></div><div class="qty"><button type="button" onclick="updateQty(${idx},-1)">−</button><span>${i.quantity}</span><button type="button" onclick="updateQty(${idx},1)">+</button></div></div>`).join('');$('cartSubtotal').textContent=money(subtotal);$('cartDelivery').textContent=delivery?money(delivery):'FREE';$('cartTotal').textContent=money(subtotal+delivery)}
function updateQty(i,d){const item=cart[i];if(!item)return;const p=products.find(x=>String(x.id)===String(item.id));const max=productStock(p)||Number(item.stock)||99;item.quantity+=d;if(item.quantity<=0)cart.splice(i,1);else if(item.quantity>max){item.quantity=max;toast('Maximum available stock: '+max)}saveCart()}
function openCart(){if($('cart'))$('cart').classList.add('open');if($('overlay'))$('overlay').classList.add('show')}
function closeAll(){if($('cart'))$('cart').classList.remove('open');if($('checkout'))$('checkout').classList.remove('show');if($('overlay'))$('overlay').classList.remove('show')}
function chooseService(n){const select=$('serviceSelect');if(select)select.value=n;const book=$('book');if(book){window.location.hash='book';setTimeout(()=>{book.scrollIntoView({behavior:'smooth',block:'start'});if(select)select.focus()},50)}}
function orderSummary(){return cart.map(i=>`${i.name} x${i.quantity} @ ${money(i.price)}`).join(' | ')}
async function placeOrder(e){e.preventDefault();if(!cart.length)return toast('Your cart is empty');const result=$('orderResult');result.textContent='Sending your order…';const d=Object.fromEntries(new FormData(e.target).entries());const subtotal=cart.reduce((a,b)=>a+Number(b.price)*b.quantity,0),delivery=subtotal>=5000?0:300,total=subtotal+delivery;const orderNo='NH-'+Date.now().toString().slice(-8);const itemText=orderSummary();const address=d.delivery_address||'';const order={order_number:orderNo,customer_name:d.customer_name,phone_number:d.phone,country:d.country||'Kenya',town:d.town,delivery_address:address,subtotal,delivery_fee:delivery,total_amount:total};const r=await sb.from('orders').insert(order);if(r.error){result.textContent='We could not send the order right now. Please try again.';console.error('ORDER INSERT ERROR',r.error);return}cart=[];saveCart();e.target.reset();result.innerHTML=`<b>Order received successfully.</b><br>Order number: ${escapeHtml(orderNo)}<br>Items: ${escapeHtml(itemText)}<br>We will contact you to confirm delivery.`;toast('Order received');setTimeout(closeAll,2200)}
async function submitService(e){e.preventDefault();const result=$('serviceResult');result.textContent='Sending your booking…';const d=Object.fromEntries(new FormData(e.target).entries());const payload={service_name:d.service_name,customer_name:d.customer_name,phone:d.phone,vehicle:d.vehicle,preferred_date:d.preferred_date||null,preferred_time:d.preferred_time||null,location:d.location,note:d.note||null,status:'pending'};const r=await sb.from('service_requests').insert(payload);if(r.error){result.textContent='We could not send the booking right now. Please try again.';console.error('SERVICE INSERT ERROR',r.error);return}e.target.reset();result.innerHTML='<b>Service booking received.</b><br>We will contact you to confirm the appointment.';toast('Booking received')}
async function load(){try{const pr=await sb.from('products').select('*').order('created_at',{ascending:false});if(pr.error){$('products').innerHTML='<div class="empty">We could not load products. Please refresh the page.</div>';console.error('PRODUCT ERROR',pr.error)}else{products=pr.data||[];renderProducts()}const sr=await sb.from('services').select('*').eq('is_active',true).order('created_at',{ascending:true});if(!sr.error)services=sr.data||[];else console.error('SERVICE ERROR',sr.error);renderServices();renderCart()}catch(err){console.error('LOAD ERROR',err);if($('products'))$('products').innerHTML='<div class="empty">We could not load products. Please refresh the page.</div>';renderServices();renderCart()}}
function init(){if($('cartBtn'))$('cartBtn').onclick=openCart;if($('closeCart'))$('closeCart').onclick=closeAll;if($('closeCheckout'))$('closeCheckout').onclick=closeAll;if($('overlay'))$('overlay').onclick=closeAll;if($('checkoutBtn'))$('checkoutBtn').onclick=()=>{if(!cart.length)return toast('Your cart is empty');$('checkout').classList.add('show');$('overlay').classList.add('show')};if($('search'))$('search').oninput=e=>{const q=e.target.value.toLowerCase();renderProducts(products.filter(p=>(p.name+' '+(p.category||'')+' '+(p.description||'')).toLowerCase().includes(q)))};if($('products'))$('products').addEventListener('click',e=>{const btn=e.target.closest('.productAddBtn');if(!btn)return;const product=products.find(x=>String(x.id)===String(btn.dataset.productId));addToCart(product)});if($('servicesGrid'))$('servicesGrid').addEventListener('click',e=>{const btn=e.target.closest('.serviceBookBtn');if(!btn)return;chooseService(btn.dataset.serviceName)});if($('checkoutForm'))$('checkoutForm').onsubmit=placeOrder;if($('serviceForm'))$('serviceForm').onsubmit=submitService;if($('waLink')){$('waLink').href='https://wa.me/'+WHATSAPP;$('waLink').textContent='WhatsApp 0769 604 872'}if($('contactWa'))$('contactWa').href='https://wa.me/'+WHATSAPP;renderServices();renderCart();load()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();